apiVersion: apps/v1
kind: Deployment
metadata:
  name: votacao-apps
  namespace: votacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votacao-apps
  template:
    metadata:
      labels:
        app: votacao-apps
    spec:
      containers:
        # container da aplicação de votação
        - image: kodekloud/examplevotingapp_vote:v1
          name: votacao-app
          ports:
            - containerPort: 80
              name: votacao-app
        # conatainer da aplicação de resultado
        - image: kodekloud/examplevotingapp_result:v1
          name: resultado-app
          ports:
            - containerPort: 8080
              name: resultado-app
        # container do worker
        - image: kodekloud/examplevotingapp_worker:v1
          name: worker
          
 