apiVersion: v1
kind: Pod
metadata:
  name: votacao-dbs
  namespace: votacao
spec:
  containers:
    # containar do postgres
    - image: postgres:9.4
      name: postgres
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      ports:
        - containerPort: 5432
          name: postgres
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
    # container do redis
    - image: redis:alpine
      name: redis
      ports:
        - containerPort: 6379
          name: redis
      volumeMounts:
        - mountPath: /data
          name: redis-data
    nodeSelector:
      tiposvc: db  

  # volumes para persistência de dados  
  volumes:
    - name: db-data
      emptyDir: {}
    - name: redis-data
      emptyDir: {}
          
# colocação dos serviços para acesso externo
# serviço do postgres
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-svc
  namespace: votacao
spec:
  type: ClusterIP
  ports:
  - name: "postgres-svc"
    port: 5432
    targetPort: 5432
# serviço do redis
---
kind: Service
apiVersion: v1
metadata:
  name: redis-svc
  namespace: votacao
spec:
  type: ClusterIP
  ports:
  - name: "redis-svc"
    port: 6379
    targetPort: 6379

