apiVersion: v1
kind: Pod
metadata:
  name: votacao-postgres
spec:
  containers:
    # containar do postgres
    - image: postgres:9.4
      name: postgres
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      ports:
        - containerPort: 5432
          name: postgres
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
  nodeSelector:
    tiposvc: db  

  # volumes para persistência de dados  
  volumes:
    - name: db-data
      emptyDir: {}
          
# colocação dos serviços para acesso externo
# serviço do postgres
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-svc
  namespace: votacao
spec:
  type: ClusterIP
  ports:
  - name: "postgres-svc"
    port: 5432
    targetPort: 5432
