apiVersion: v1
kind: Pod
metadata:
  name: app-biblioteca
  namespace: biblioteca
spec:
  containers:
    - name: banco-dados
      image: alpine/postgres
      #imagepullpolicy: IfNotPresent
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: postgresdb
          mountPath: /var/lib/postgresql/data
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
    - name: loki
      image: grafana/loki:latest
      ports:
        - containerPort: 3100
      volumeMounts:
      - name: fluentd-config
        mountPath: /etc/fluent/fluent.conf
  - name: app-web
    image: marcelopinto350/bibpub:1.0
    - containerPort: 8000
    env:
    - name: DATABASE_URL
      value: postgres://banco-dados:<senha_do_postgres>@banco-dados:5432
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: static
      mountPath: /usr/share/nginx/html
  volumes:
    - name: postgresdb
      persistentVolumeClaim:
        claimName: postgres-pvc
    - name: fluentd-config
      configMap:
        name: fluentd-config 
#  - name: static
#    secret:
#      secretName: static-content
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: biblioteca
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: biblioteca
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  type: ClusterIP

