apiVersion: v1
kind: Pod
metadata:
  name: app-biblioteca
  namespace: biblioteca
spec:
  containers:
    - name: banco-dados
      image: postgres:alpine
      #imagepullpolicy: IfNotPresent
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: postgresdb
          mountPath: /var/lib/postgresql/data
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB

    - name: app-bibpub
      image: marcelopinto350/bibpub:1.2
      #depends_on:
      #  - banco-dados
      env:
        - name: POSTGRES_HOST
          value: "postgres-svc:default"
        - name: POSTGRES_PORT
          value: "5432"
      ports:
      - containerPort: 8000
    
    - name: fluentd
      image: fluentd:latest
      ports:
        - containerPort: 3100
      volumeMounts:
      - name: logs
        mountPath: /var/log/bibpub
      command:
      - "fluentd"
      - "-c"
      - "/fluentd/etc/fluentd.conf"

    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
      volumeMounts:
      - name: logs
        mountPath: /var/log/nginx
  
  volumes:
    - name: postgresdb
      persistentVolumeClaim:
        claimName: postgres-pvc
    - name: fluentd-config
      configMap:
        name: fluentd-config 
    - name: logs
      emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: postgres-svc
  namespace: biblioteca
spec:
  # selector:
  #  app: postgres
  ports:
    - port: 5432
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: biblioteca-svc
  namespace: biblioteca
spec:
  #selector:
  #  app: app-biblioteca
  ports:
    - port: 8000
  type: NodePort

